/** Central route paths — use instead of hardcoded strings in links and redirects. */
export const ROUTES = {
  home: "/",
  login: "/login",
  dashboard: "/dashboard",
  hiringJobs: "/hiring/jobs",
  hiringJobNew: "/hiring/jobs/new",
  hiringJob: (jobId: string) => `/hiring/jobs/${jobId}`,
  jobs: "/jobs",
  job: (id: string) => `/jobs/${id}`,
  jobPipeline: (id: string) => `/jobs/${id}/pipeline`,
  jobSettings: (id: string) => `/jobs/${id}/settings`,
  jobsNew: "/jobs/new",
  candidates: "/candidates",
  candidate: (id: string) => `/candidates/${id}`,
  applicants: "/applicants",
  applicant: (id: string) => `/applicants/${id}`,
  interviews: "/interviews",
  interview: (id: string) => `/interviews/${id}`,
  interviewIntelligence: "/interviews/intelligence",
  assessments: "/assessments",
  schedules: "/schedules",
  questionPool: "/question-pool",
  reports: "/reports",
  analytics: "/analytics",
  enterprises: "/enterprises",
  compare: "/compare",
  roles: "/roles",
  role: (id: string) => `/roles/${id}`,
  settings: "/settings",
  settingsAudit: "/settings/audit",
  usersRoles: "/users-roles",
  migrations: "/migrations",
  localization: "/localization",
  meet: "/meet",
  meetRoom: (roomId: string) => `/meet/${roomId}`,
} as const;
